apiVersion: v1
kind: Service
metadata:
  name: aura-service
spec:
  type: NodePort
  selector:
    app: aura
  ports:
    - port: 80          # Service port (inside cluster)
      targetPort: 8080  # Container / Gunicorn port
      nodePort: 30054   # NodePort you requested
